### ISSUE TITLE
Gravity and periodic boundary conditions for relperm upscaling

### ISSUE THREAD

**Issue by lkerrand** [OPM/opm-upscaling#165] opened 2015-11-04 14:25 UTC
In the last commit I added two references solutions and one grid:
- 16cells.grdecl
- upscale_relperm_gravityDailyVersion_16cells.txt
- upscale_relperm_gravitySBEDVersion_16cells.txt

It has been necessary to create a new grid with SBED to use the original relperm upscaling code and compare the results with the ones obtained with the daily version of the code. It shows significant discrepancies: the daily version of the program does not seem to take the gravity effect into account contrary to SBED.

In addition, the periodic option for the boundary conditions has been tested with the Dailly and installed version of the relperm upscaling code with the following grid:
- Eightscells
- Hummocky
- 16cells
- 27cellsIso
- PeriodicTilted
- benchmark_tiny_grid

If the daily version program gives results with the Eightcells grid and the 27cellsIso grid (and the installed version gives results for the 27cellsIsso and benchmark grids), most of the time the program run and then the "core dumped" (or do not run at all for the daily version with the 16cells grid).

**Comment by bska** [comment] 2015-11-16 18:25
> use the original relperm upscaling code

Just out of curiosity, Do you have any idea of what time point corresponds to the by **original** relperm upscaling code?  I.e., whether it was based on sources from one year ago, three years ago, five years ago or ten years ago?

**Comment by alfbr** [comment] 2015-11-16 19:49
We can double check tomorrow, but I believe we went back to the sang based code to get a reference solution.

**Comment by alfbr** [comment] 2015-11-17 10:22
Just checked. We seem to have incorrect results all the way back to May 2012. Louis can send you a test case.

**Comment by bska** [comment] 2015-11-17 11:23
> We seem to have incorrect results all the way back to May 2012.

Okay, that does at least narrow the search region a bit.

> Louis can send you a test case.

Yes please.

**Comment by bska** [comment] 2015-11-18 08:58
There's a wonderful dichotomy in the discretisation of the gravity term in the `upscale_relperm` utility (and maybe others, I haven't verified this).  While the grid constructor assumes that all lengths and depths are given in units of metres the gravity term discretisation assumes that the depths are given in units of [centimetres](https://github.com/OPM/opm-upscaling/blob/master/opm/upscaling/RelPermUtils.cpp#L466-L468).

I think I know the historical reason for this assumption.  All of the models used in the original development of the upscaling utility used centimetre length scales.  Would you mind, as a quick check/hack, to run the tests using
```
-gravity 981
```
rather than `9.81` and see if you get better results this way?

**Comment by bska** [comment] 2016-03-16 19:52
Today I finally had occasion to look into this more closely.  My preliminary conclusion is that the gravity handling is fundamentally broken (not to mention, [explicitly turned off](https://github.com/OPM/opm-upscaling/blob/master/opm/upscaling/UpscalerBase_impl.hpp#L231-L232) in the low-level upscaling code, despite being actively queried in [`upscale_relperm.cpp`](https://github.com/OPM/opm-upscaling/blob/master/examples/upscale_relperm.cpp#L294)).

Moreover, some parts of the code assume centi-metre length scales, while others use metres.  That, in turn, affects pressure gradients and flow rates--at least when the flow is driven by pressure drops.

Fixing this will require days of implementation work--not to mention substantial testing efforts--and will affect code in other OPM modules.

**Comment by bska** [comment] 2016-04-13 10:03
I have finished my initial implementation of this feature so I'd like to enlist some testing help to assess the state of completion.  At this time I'm a little reluctant to create a PR because there may still be a lot of work remaining depending on the testing outcome.  Therefore, if you would like to help test, please use the following commands to access my branch
```sh
git checkout -b bska_capillary-gravity-upscaling
git pull git://github.com/bska/opm-upscaling.git capillary-gravity-upscaling
```

**Comment by atgeirr** [comment] 2016-04-13 11:29
Excellent! I can confirm that the branch builds (when merged on top of master, to account for the opm-parser API change). There is a test failure: 

```
14/16 Test #14: upscale_relperm_BCf_pts30_surfTens11_stoneAniso_stoneAniso_27cellsAniso ............................***Failed    0.18 sec
```

This is expected since this test essentially is a regression test, and the fixed bugs *should* be expected to change the results for some of the tests.

**Comment by atgeirr** [comment] 2017-04-11 05:40
This was fixed a year ago, closing.

**Closed by atgeirr** 2017-04-11 05:40 UTC
